### ISSUE TITLE
Review of jyasskin's draft

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#74] opened 2016-04-01 08:11 UTC
I reviewed https://rawgit.com/jyasskin/permissions/allow-choosers/index.html
1. Everything that is associated with a permission should default to the "binary" (rename to boolean?) options. There's no need to repeat that for each of them.
2. Since the majority are boolean, there should be a simple way to get and set the state of boolean permissions. See https://notifications.spec.whatwg.org/ for how simple this can be.
3. permissions.request() should not be available in workers I think.

**Comment by jyasskin** [comment] 2016-04-01 16:44
I've done (1) in #66; the rest should wait for separate PRs.

**Comment by marcoscaceres** [comment] 2021-06-17 05:20
2 above is duplicate of https://github.com/w3c/permissions/issues/42 ... 1 was done in #66, and 3 doesn't apply as there is no .request().

**Closed by marcoscaceres** 2021-06-17 05:20 UTC
